// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeLog(arg1) {
  return window['go']['main']['App']['AnalyzeLog'](arg1);
}

export function GetDefaultPath() {
  return window['go']['main']['App']['GetDefaultPath']();
}

export function SelectLogDirectory() {
  return window['go']['main']['App']['SelectLogDirectory']();
}

export function SelectLogFile() {
  return window['go']['main']['App']['SelectLogFile']();
}
