// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeLog(arg1:main.AnalyzeRequest):Promise<main.ParseResult>;

export function GetDefaultPath():Promise<string>;

export function SelectLogDirectory():Promise<string>;

export function SelectLogFile():Promise<string>;
